/* DDL(Data Definition Language)
 * - 데이터 정의어
 * - 객체를 정의하기 위한 CREATE(생성), ALTER(수정), DROP(제거) 구문이 있다.
 * - ORACLE에서 사용하는 객체: TABLE, VIEW, SEQUENCE, FUNCTION, INDEX, PROCEDUAL, USER... 등
 */
-- 생성방법
CREATE TABLE 테이블명(
  	컬럼명 데이터타입(크기) [제약조건]
  	, ...(반복)
);


CREATE  SAMPLE_T(
	u_id NUMBER 
	, NAME VARCHAR2(50)
	, AGE NUMBER(3)
	, GENDER CHAR(1)
	, BIRTHDAY DATE
);

COMMENT ON COLUMN SAMPLE_T.U_ID IS '사용자 구분 아이디';
COMMENT ON COLUMN SAMPLE_T.NAME IS '사용자 이름';
COMMENT ON COLUMN SAMPLE_T.AGE IS '사용자 나이';
COMMENT ON COLUMN SAMPLE_T.GENDER IS '사용자 성별';
COMMENT ON COLUMN SAMPLE_T.BIRTHDAY IS '사용자 생년월일';

--TABLE이 생성되었는지 확인
SELECT * FROM SAMPLE_T;
SELECT * FROM USER_ALL_TABLES WHERE TABLE_NAME = 'SAMPLE_T';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLE_T';
SELECT * FROM USER_COL_CEMMENTS WHERE TABLE_NAME = 'SAMPLE_T';

DROP TABLE SAMPLE_T;
