CREATE TABLE EMP_COMMISSION 
 AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
	  FROM EMPLOYEES
	 WHERE 1 = 0;
CREATE TABLE EMP_NO_COMMISSION 
 AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
	  FROM EMPLOYEES
	 WHERE 1 = 0;
	 
INSERT ALL 
WHEN COMMISSION_PCT IS NOT NULL THEN
	INTO EMP_COMMISSION VALUES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT)
WHEN COMMISSION_PCT IS NULL THEN
	INTO EMP_NO_COMMISSION VALUES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
FROM  EMPLOYEES;


/*** [UPDATE] 예시1 ***
 * UPDATE 테이블명
 * 	  SET 컬럼명 = (SELECT 컬럼명 FROM 테이블명 WHERE 조건)
 *  WHERE 조건;
 */
SELECT * FROM EMP_COMMISSION;
SELECT * FROM EMP_NO_COMMISSION;
--EMP_COMMISSION 테이블에서 모든 사원에 대해 COMMISSION_PCT를 0.02증가시킨다.
UPDATE EMP_COMMISSION
	SET COMMISSION_PCT = COMMISSION_PCT + 0.02;

--EMP_NO_COMMISSION 테이블에서 SALARY가 4000이하인 사원들에 대해 SALARY를 200 증가시킨다.
SELECT * FROM EMP_NO_COMMISSION WHERE SALARY <= 4000;

UPDATE EMP_NO_COMMISSION
   SET SALARY = SALARY + 200
 WHERE SALARY <= 4000;

/*** [UPDATE] 예시2 ***
 * UPDATE 테이블명
 * 	  SET 컬럼명 = 바꿀 값
 *  WHERE 컬럼명 IN (SELECT 컬럼명 FROM 테이블명 WHERE 조건);
 */
SELECT * FROM EMP_COMMISSION 
WHERE EMPLOYEE_ID IN(SELECT MANAGER_ID FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL);
SELECT * FROM EMP_NO_COMMISSION 
WHERE EMPLOYEE_ID IN(SELECT MANAGER_ID FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL);

UPDATE EMP_COMMISSION 
   SET SALARY = SALARY + 100
 WHERE EMPLOYEE_ID IN(SELECT MANAGER_ID FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL);

UPDATE EMP_NO_COMMISSION 
   SET SALARY = SALARY + 100
 WHERE EMPLOYEE_ID IN(SELECT MANAGER_ID FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL);
