/* EMPLOYEES 테이블의 구조를 복사한 새로운 테이블 2개 만들기
 * 	- EMP_COMMISSION 테이블: EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
 * 	- EMP_NO_COMMSSION 테이블: EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
 */
SELECT * FROM EMPLOYEES;
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

/*CREATE TABLE EMP_COMMISSION(
	  EMPLOYEE_ID	 NUMBER
	, FIRST_NAME	 VARCHAR2(20)
	, LAST_NAME		 VARCHAR2(25)
	, SALARY		 NUMBER
	, COMMISSION_PCT NUMBER
);
CREATE TABLE EMP_NO_COMMISSION(
	  EMPLOYEE_ID	 NUMBER
	, FIRST_NAME	 VARCHAR2(20)
	, LAST_NAME		 VARCHAR2(25)
	, SALARY		 NUMBER
);
 */

CREATE TABLE EMP_COMMISSION 
 AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
	  FROM EMPLOYEES
	 WHERE 1 = 0;
CREATE TABLE EMP_NO_COMMISSION 
 AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
	  FROM EMPLOYEES
	 WHERE 1 = 0;

/* 위와 같이 테이블을 생성한 후, EMPLOYEES 테이블이 가지고 있는 모든 행 데이터를 추가
 * 	1. INSERT INTO...(SELECT... 구문을 사용하여 추가하기
 * 	2. INSERT ALL INTO... 구문을 사용하여 추가하기
 * 
 * 위의 작업을 진행할 때 DELETE FROM EMP_COMMISSION; DELETE FROM EMP_NO_COMMISSIO; 을 작업 후 진행한다. 
 */
SELECT * FROM EMP_COMMISSION;
SELECT * FROM EMP_NO_COMMISSION;

DROP TABLE EMP_COMMISSION;
DROP TABLE EMP_NO_COMMISSION;

-- INSERT INTO는 TABLE을 미리 만들어 놓아야 함
--[INSERT INTO] 예시 1
INSERT INTO EMP_COMMISSION(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT) 
	 VALUES(컬럼 순서에 따른 값을 차례로 넣는다. ↑)
	
--[INSERT INTO] 예시 2
INSERT INTO	EMP_NO_COMMISSION
	 VALUES(컬럼 순서에 따른 값을 차례로 넣는다.) --컬럼은 TABLE 만들 때 이미 설정해 두었어야 한다.
	 
--***[INSERT INTO] 예시 3***
INSERT INTO EMP_COMMISSION(
	SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
	FROM EMPLOYEES
);


--[INSERT ALL] 예시 1: TABLE을 미리 안 만들어 놓아도 됨.
CREATE TABLE EMP_COMMISSION
	AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
	   FROM EMPLOYEES;
	  
CREATE TABLE EMP_NO_COMMISSION
	AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
	   FROM EMPLOYEES;
	 
	 
--[INSERT ALL] 예시 2 
INSERT ALL 
INTO EMP_COMMISSION VALUES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT)
INTO EMP_NO_COMMISSION VALUES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
FROM  EMPLOYEES;
--조건 붙이기
INSERT ALL 
WHEN COMMISSION_PCT IS NOT NULL THEN
	INTO EMP_COMMISSION VALUES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT)
WHEN COMMISSION_PCT IS NULL THEN
	INTO EMP_NO_COMMISSION VALUES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT
FROM  EMPLOYEES;


