SELECT FIRST_NAME || ' '||LAST_NAME AS 이름,
		REPLACE(PHONE_NUMBER, '.', '-') AS 전화번호,
		LOWER(EMAIL ||'@example.com') AS 이메일,
		TO_CHAR(HIRE_DATE, 'YYYY"년 "MONDD"일"') AS 고용일,
		TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12, 1) AS 근년일수,
	  --FLOOR(SYSDATE, HIRE_DATE) AS 근속일 
	  --FLOOR(MONTH_BETWEEN(SYSDATE, HIRE_DATE)) AS 근속월 
	  --FLOOR(SYSDATE, HIRE_DATE) AS 근속일 
		'년' AS YEAR,
		TO_CHAR(TRUNC(SALARY * (1 + NVL(COMMISSION_PCT, 0))*1260, -3), '999,999,999L') AS 연봉
FROM EMPLOYEES
ORDER BY HIRE_DATE ;

SELECT FIRST_NAME , SALARY,COMMISSION_PCT ,
		TO_CHAR(TRUNC(SALARY * (1 + NVL(COMMISSION_PCT, 0))*12, -3), '999,999,999L') AS 연봉
FROM EMPLOYEES;


SELECT NVL(SUBSTR(PHONE_NUMBER, 1, 3), '총계') AS 회선번호,
	 --SUBSTR(PHONE_NUMBER, 1, 3) AS 회선번호, 
		COUNT(*) AS 회선수
FROM EMPLOYEES
GROUP BY ROLLUP(SUBSTR(PHONE_NUMBER, 1, 3))
ORDER BY 회선번호;

SELECT MANAGER_ID, COUNT(*)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY ROLLUP (MANAGER_ID);
