/** SEQUENCE: 자동 번호 발생기
 * 	- STRAT WITH:   처음 시작할 숫자
 *  - INCREMENT BY: 증가시킬 숫자
 * 	- MAXVALUE:	    최대
 *  - MINVALUE:     최소
 *  - CYCLE/ NOCYCLE: 
 *  - CACHE/ NOCACHE:
 * 
 * - 시퀀스명.CURRVAL/시퀀스명.NEXTVAL: 시퀀스의 현재숫자/ 다음숫자
 * **/

--NO MINVALUE/ NOCYCLE
CREATE SEQUENCE SEQ_TEST
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE;

SELECT SEQ_TEST.CURRVAL FROM DUAL;
SELECT SEQ_TEST.NEXTVAL FROM DUAL;

DROP SEQUENCE SEQ_TEST;

--MINVALUE/ CYCLE
CREATE SEQUENCE SEQ_TEST
START WITH 300
INCREMENT BY 5
MAXVALUE 310
MINVALUE 290
CYCLE
NOCACHE;

SELECT SEQ_TEST.CURRVAL FROM DUAL;
SELECT SEQ_TEST.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ_TEST CACHE 100;
SELECT SEQ_TEST.CURRVAL FROM DUAL;
SELECT SEQ_TEST.NEXTVAL FROM DUAL;

SELECT * FROM SAMPLE_T;
--현재 시퀀스(SEQ_TEST.NEXTVAL)의 값으로 TABLE에 추가가 됨
--테이블의 다음번호로 바로 들어가지 않음
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '최다연', 'F', 27);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '최지우', 'M', 25);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '이언주', 'F', 33);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL, '한선우', 'M', 40);