/* VIEW 
 * CREATE OR REPLACE VIEW: 없으면 만들고 있으면 대체하기
 * FORCE/NOFORCE
 * WITH CHECK OPTION: 옵션을 설정한 컬럼의 값을 수정 불가능하게 함
 * 					  WHERE절에서 설정한 값을 UPDATE하면서 넘어가게 되면 수정 불가능
 * WITH READ ONLY: 뷰에 대해 조회만 가능하고 삽입, 수정, 삭제 등은 불가능하게 함
 */

DROP TABLE SAMPLE_T;
CREATE TABLE SAMPLE_T(
	ID NUMBER PRIMARY KEY
	, NAME VARCHAR2(30) NOT NULL
	, GENDER CHAR(1) CHECK(GENDER IN ('M','F'))
	, AGE NUMBER DEFAULT (0) NOT NULL
);
INSERT INTO SAMPLE_T VALUES(1, '최다연', 'F', 27);
INSERT INTO SAMPLE_T VALUES(2, '최지우', 'M', 25);
INSERT INTO SAMPLE_T VALUES(3, '이언주', 'F', 33);
INSERT INTO SAMPLE_T VALUES(4, '한선우', 'M', 40);

CREATE OR REPLACE VIEW VIEW_SAMPLE_T
AS SELECT NAME, GENDER, AGE
FROM SAMPLE_T 
WHERE AGE BETWEEN 27 AND 30 
WITH CHECK OPTION;
--WITH READ ONLY;
--1. AS SELECT ID, NAME, GENDER FROM SAMPLE_T;
-- ↓ 가상열: 컬럼명에 산술식 기입 가능
--2. AS SELECT  NAME, GENDER, AGE + 1 AS AGE FROM SAMPLE_T; 

--VIEW TABLE 존재여부 확인
SELECT * FROM VIEW_SAMPLE_T; 
SELECT * FROM USER_VIEWS;
SELECT * FROM SAMPLE_T;

--VIEW 테이블에서 지우면 원 테이블에서도 지워짐
DELETE FROM VIEW_SAMPLE_T;
ROLLBACK;

--VIEW TABLE 수정-> 원래 테이블이 수정됨
--가상열(2.)을 수정하고자 한다면 불가능
UPDATE VIEW_SAMPLE_T SET AGE = AGE + 4;
 
--V_SAMPLE_T에는 ID컬럼은 없지만 이 컬럼을 빼놓고 데이터를 추가한다면, 
--ID는 NULL이 되므로 에러가 남.
INSERT INTO VIEW_SAMPLE_T VALUES(5, '이기석', 'M', 36);
